# Generated by Django 3.2 on 2021-04-14 16:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(default='', max_length=220)),
                ('client_email', models.EmailField(default='', max_length=220)),
                ('client_nif', models.CharField(default='000000000', max_length=9)),
                ('client_contract_begin', models.DateField(default=datetime.date(2021, 4, 14), verbose_name='Data de inicio de contracto')),
                ('client_contract_end', models.DateField(default=datetime.date(2021, 4, 14), verbose_name='Data de fim de contracto')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(default='', max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='TariffBTN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btn_tariff_ponta', models.FloatField()),
                ('btn_tariff_cheia', models.FloatField()),
                ('btn_tariff_vazio', models.FloatField()),
                ('btn_value_power', models.FloatField()),
                ('btn_tariff_date_start', models.DateField(default=datetime.date(2021, 4, 14), verbose_name='Data de inicio de contracto')),
                ('btn_tariff_date_end', models.DateField(default=datetime.date(2021, 4, 14), verbose_name='Data de fim de contracto')),
                ('btn_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.provider')),
            ],
        ),
    ]
