# Generated by Django 3.2 on 2021-04-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210414_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffbtn',
            name='btn_power',
            field=models.CharField(choices=[('1.15', '1.15'), ('3.45', '3.45'), ('4.6', '4.6'), ('5.75', '5.75'), ('6.9', '6.9'), ('10.35', '10.35'), ('13.8', '13.8'), ('17.25', '17.25'), ('20.7', '20.7'), ('27.6', '27.6'), ('34.5', '34.5'), ('41.41', '41.41')], default='', max_length=5),
        ),
    ]
