# Generated by Django 3.2 on 2021-04-14 17:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tariffbtn_btn_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffbtn',
            name='btn_cicle',
            field=models.CharField(choices=[('SCiclo', 'Sem Ciclo'), ('Opc', 'Opcional'), ('Bi-H', 'Bi-Horario'), ('Tri-H', 'Tri-Horario')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='tariffbtn',
            name='btn_tariff_date_end',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de fim'),
        ),
        migrations.AlterField(
            model_name='tariffbtn',
            name='btn_tariff_date_start',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de inicio'),
        ),
    ]
