# Generated by Django 3.2 on 2021-04-14 17:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210414_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='TariffMT_BTE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mt_bte_tension_level', models.CharField(choices=[('BTE', 'BTE'), ('MT', 'MT')], default='', max_length=3)),
                ('mt_bte_cicle', models.CharField(choices=[('Diario', 'Diario'), ('Semanal', 'Semanal'), ('Opcional', 'Opcional')], default='', max_length=10)),
                ('mt_bte_tariff_ponta', models.FloatField()),
                ('mt_bte_tariff_cheia', models.FloatField()),
                ('mt_bte_tariff_vazio', models.FloatField()),
                ('mt_bte_tariff_s_vazio', models.FloatField()),
                ('mt_bte_tariff_p_h_p', models.FloatField()),
                ('mt_bte_tariff_date_start', models.DateField(default=django.utils.timezone.now, verbose_name='Data de inicio')),
                ('mt_bte_tariff_date_end', models.DateField(default=django.utils.timezone.now, verbose_name='Data de fim')),
                ('mt_bte_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.provider')),
            ],
        ),
    ]
