# Generated by Django 3.2 on 2021-04-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_tariffmt_bte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_nif',
            field=models.CharField(default='000000000', max_length=9, unique=True),
        ),
    ]
