# Generated by Django 3.2 on 2021-04-16 14:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_client_client_nif'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff_BTE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mt_bte_cicle', models.CharField(choices=[('Diario', 'Diario'), ('Semanal', 'Semanal')], default='', max_length=10)),
                ('mt_bte_tariff_date_start', models.DateField(default=django.utils.timezone.now, verbose_name='Data de inicio')),
                ('mt_bte_tariff_date_end', models.DateField(default=django.utils.timezone.now, verbose_name='Data de fim')),
                ('bte_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.provider')),
            ],
        ),
        migrations.CreateModel(
            name='Tariff_BTN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btn_power', models.CharField(choices=[('1.15', '1.15'), ('3.45', '3.45'), ('4.6', '4.6'), ('5.75', '5.75'), ('6.9', '6.9'), ('10.35', '10.35'), ('13.8', '13.8'), ('17.25', '17.25'), ('20.7', '20.7'), ('27.6', '27.6'), ('34.5', '34.5'), ('41.40', '41.40')], default='', max_length=5)),
                ('btn_price_day', models.FloatField()),
                ('btn_cicle', models.CharField(choices=[('Simp', 'Simples'), ('Bi-H', 'Bi-Horario'), ('Tri-H', 'Tri-Horario')], default='', max_length=5)),
                ('btn_tariff_date_start', models.DateField(default=django.utils.timezone.now, verbose_name='Data de inicio')),
                ('btn_tariff_date_end', models.DateField(default=django.utils.timezone.now, verbose_name='Data de fim')),
                ('btn_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.provider')),
            ],
        ),
        migrations.CreateModel(
            name='Tariff_MT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mt_cicle', models.CharField(choices=[('c/f', 'semanal c/feriados'), ('o/c', 'semanal c/opcao cliente')], default='', max_length=3)),
                ('mt_tariff_date_start', models.DateField(default=django.utils.timezone.now, verbose_name='Data de inicio')),
                ('mt_tariff_date_end', models.DateField(default=django.utils.timezone.now, verbose_name='Data de fim')),
                ('mt_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.provider')),
            ],
        ),
        migrations.RemoveField(
            model_name='tariffmt_bte',
            name='mt_bte_provider',
        ),
        migrations.AlterField(
            model_name='client',
            name='client_nif',
            field=models.CharField(default='PT000000000', max_length=11, unique=True),
        ),
        migrations.DeleteModel(
            name='TariffBTN',
        ),
        migrations.DeleteModel(
            name='TariffMT_BTE',
        ),
    ]
