# Generated by Django 3.2 on 2021-04-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210416_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_email',
            field=models.EmailField(default='', max_length=220, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_name',
            field=models.CharField(default='', max_length=220, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_nif',
            field=models.CharField(default='PT000000000', max_length=11, unique=True, verbose_name='NIF'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='provider_name',
            field=models.CharField(default='', max_length=220, verbose_name='Fornecedor'),
        ),
        migrations.AlterField(
            model_name='tariff_bte',
            name='bte_cicle',
            field=models.CharField(choices=[('Diario', 'Diario'), ('Semanal', 'Semanal')], default='', max_length=10, verbose_name='Ciclo'),
        ),
        migrations.AlterField(
            model_name='tariff_btn',
            name='btn_cicle',
            field=models.CharField(choices=[('Simp', 'Simples'), ('Bi-H', 'Bi-Horario'), ('Tri-H', 'Tri-Horario')], default='', max_length=5, verbose_name='Ciclo'),
        ),
        migrations.AlterField(
            model_name='tariff_btn',
            name='btn_power',
            field=models.CharField(choices=[('1.15', '1.15'), ('3.45', '3.45'), ('4.6', '4.6'), ('5.75', '5.75'), ('6.9', '6.9'), ('10.35', '10.35'), ('13.8', '13.8'), ('17.25', '17.25'), ('20.7', '20.7'), ('27.6', '27.6'), ('34.5', '34.5'), ('41.40', '41.40')], default='', max_length=5, verbose_name='Potencia contratada'),
        ),
        migrations.AlterField(
            model_name='tariff_btn',
            name='btn_price_day',
            field=models.FloatField(verbose_name='Preço/dia'),
        ),
        migrations.AlterField(
            model_name='tariff_mt',
            name='mt_cicle',
            field=models.CharField(choices=[('c/f', 'semanal c/feriados'), ('o/c', 'semanal c/opcao cliente')], default='', max_length=3, verbose_name='Ciclo'),
        ),
    ]
