# Generated by Django 3.2 on 2021-04-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_tariff_btn_btn_price_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff_mt',
            name='mt_tarrif_cheias',
            field=models.FloatField(default=0.0, verbose_name='Horas Cheias'),
        ),
        migrations.AddField(
            model_name='tariff_mt',
            name='mt_tarrif_pontas',
            field=models.FloatField(default=0.0, verbose_name='Horas Ponta'),
        ),
        migrations.AddField(
            model_name='tariff_mt',
            name='mt_tarrif_super_vazio',
            field=models.FloatField(default=0.0, verbose_name='Horas de super vazio'),
        ),
        migrations.AddField(
            model_name='tariff_mt',
            name='mt_tarrif_vazio_normal',
            field=models.FloatField(default=0.0, verbose_name='Horas de vazio normal'),
        ),
    ]
