# Generated by Django 3.2 on 2021-04-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210416_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff_bte',
            name='bte_tarrif_cheias',
            field=models.FloatField(default=0.0, verbose_name='Horas Cheias'),
        ),
        migrations.AddField(
            model_name='tariff_bte',
            name='bte_tarrif_pontas',
            field=models.FloatField(default=0.0, verbose_name='Horas Ponta'),
        ),
        migrations.AddField(
            model_name='tariff_bte',
            name='bte_tarrif_super_vazio',
            field=models.FloatField(default=0.0, verbose_name='Horas de super vazio'),
        ),
        migrations.AddField(
            model_name='tariff_bte',
            name='bte_tarrif_vazio_normal',
            field=models.FloatField(default=0.0, verbose_name='Horas de vazio normal'),
        ),
        migrations.AddField(
            model_name='tariff_btn',
            name='btn_bi_f_vazio',
            field=models.FloatField(default=0.0, verbose_name='Tarrifa Fora Vazio'),
        ),
        migrations.AddField(
            model_name='tariff_btn',
            name='btn_bi_vazio',
            field=models.FloatField(default=0.0, verbose_name='Tarrifa Vazio'),
        ),
        migrations.AddField(
            model_name='tariff_btn',
            name='btn_simple',
            field=models.FloatField(default=0.0, verbose_name='Tarifa Simple'),
        ),
        migrations.AddField(
            model_name='tariff_btn',
            name='btn_tri_cheias',
            field=models.FloatField(default=0.0, verbose_name='Tarrifa Cheias'),
        ),
        migrations.AddField(
            model_name='tariff_btn',
            name='btn_tri_ponta',
            field=models.FloatField(default=0.0, verbose_name='Tarrifa Pontas'),
        ),
        migrations.AddField(
            model_name='tariff_btn',
            name='btn_tri_vazio',
            field=models.FloatField(default=0.0, verbose_name='Tarrifa Vazio'),
        ),
    ]
