# Generated by Django 3.2 on 2021-04-29 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210416_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff_bte',
            name='bte_tarrif_cheias_c_redes',
            field=models.FloatField(default=0.0, verbose_name='Horas Cheias com Redes'),
        ),
        migrations.AddField(
            model_name='tariff_bte',
            name='bte_tarrif_pontas_c_redes',
            field=models.FloatField(default=0.0, verbose_name='Horas Ponta com Redes'),
        ),
        migrations.AddField(
            model_name='tariff_bte',
            name='bte_tarrif_super_vazio_c_redes',
            field=models.FloatField(default=0.0, verbose_name='Horas de super vazio com Redes'),
        ),
        migrations.AddField(
            model_name='tariff_bte',
            name='bte_tarrif_vazio_normal_c_redes',
            field=models.FloatField(default=0.0, verbose_name='Horas de vazio normal com Redes'),
        ),
        migrations.AddField(
            model_name='tariff_mt',
            name='mt_tarrif_cheias_c_redes',
            field=models.FloatField(default=0.0, verbose_name='Horas Cheias com Redes'),
        ),
        migrations.AddField(
            model_name='tariff_mt',
            name='mt_tarrif_pontas_c_redes',
            field=models.FloatField(default=0.0, verbose_name='Horas Ponta com Redes'),
        ),
        migrations.AddField(
            model_name='tariff_mt',
            name='mt_tarrif_super_vazio_c_redes',
            field=models.FloatField(default=0.0, verbose_name='Horas de super vazio com Redes'),
        ),
        migrations.AddField(
            model_name='tariff_mt',
            name='mt_tarrif_vazio_normal_c_redes',
            field=models.FloatField(default=0.0, verbose_name='Horas de vazio normal com Redes'),
        ),
    ]
